import { z } from "zod";

const documentationReadSchema = z.object({
  documentation_type: z.enum([
    "createCustomer",
    "retrieveCustomer",
    "retrieveCustomerByExternalId",
    "updateCustomer",
    "enrollPaymentMethod",
    "retrievePaymentMethod",
    "retrieveEnrolledPaymentMethods",
    "unenrollPaymentMethod",
    "createCheckoutSession",
    "retrievePaymentMethodsForCheckoutSession",
    "createOttForCheckoutSession",
    "createPayment",
    "retrievePayment",
    "retrievePaymentByMerchantOrderId",
    "refundPayment",
    "cancelOrRefundPayment",
    "cancelOrRefundWithTransactionPayment",
    "cancelPayment",
    "authorizePayment",
    "captureAuthorizationPayment",
    "createPaymentLink",
    "retrievePaymentLink",
    "cancelPaymentLink",
    "createSubscription",
    "retrieveSubscription",
    "pauseSubscription",
    "resumeSubscription",
    "updateSubscription",
    "cancelSubscription",
    "createRecipient",
    "retrieveRecipient",
    "updateRecipient",
    "deleteRecipient",
    "createRecipientOnboarding",
    "createInstallmentPlan",
    "retrieveInstallmentPlan",
    "retrieveAllInstallmentPlans",
    "updateInstallmentPlan",
    "deleteInstallmentPlan",
    "guides",
    "web",
    "web_v_1_1",
    "android",
    "android_release_notes",
    "ios",
    "ios_release_notes",
    "unofficial.node",
    "unofficial.react",
  ]),
});

export { documentationReadSchema };
